Note: This is simplest algo (no medium alerts)

Steps for Grape Algo

Read in Data:
Check if daily avg temp is >10 Cel
If yes, Check if humidity has been >85% for 10 cons. days
To try: Check if fn works with diff settings "yellow alerts" like 80% humidity, or 9 days of >85%

In [52]:
import pandas as pd
from datetime import datetime

In [53]:
df = pd.read_csv('sensor_data_changed.csv')

In [54]:
df.head()

,sensor_id,gateway_id,timestamp,humidity,temperature,pressure,light,wind_direction,wind_speed,precipitation,battery,counter,rssi,Column1
0,W3,G7,1.591640e+12,900,80,78218,294,0,0,0,151,389,-71,NaN
1,W3,G7,1.591640e+12,900,80,78224,306,0,0,0,151,392,-71,NaN
2,W3,G7,1.591640e+12,900,80,78222,271,0,0,0,151,393,-72,NaN
3,W13,G7,1.592340e+12,900,80,100254,1007,0,0,0,155,0,-70,NaN
4,W13,G7,1.592340e+12,900,80,100252,997,0,0,0,155,1,-64,NaN

In [55]:
# Change timestamp to a date
df=df[['sensor_id',"timestamp","humidity","temperature"]]
df["date"]=df.apply(lambda row: datetime.strftime(pd.to_datetime(row["timestamp"],unit='ms'),"%Y-%m-%d"),axis=1)
df=df.drop("timestamp",axis=1)

In [56]:
df=df.sort_values(by=["sensor_id","date"])
df.head(5)

  sensor_id  humidity  temperature        date
3       W13       900           80  2020-06-16
4       W13       900           80  2020-06-16
5       W13       900           80  2020-06-16
6       W13       900           80  2020-06-16
7       W13       900           80  2020-06-16

In [57]:
# get mean daily temp, check if >10 Celsius
df["mean_daily_temp"]=df.groupby(['sensor_id',"date"])['temperature'].transform(lambda row: row.mean())
df["is_daily_temp_over_10"]=df.apply(lambda row: "above" if (row["mean_daily_temp"]/10)>10 else "below", axis=1)
df.tail(25)

,sensor_id,humidity,temperature,date,mean_daily_temp,is_daily_temp_over_10
1690,W13,760,125,2020-07-27,125.0,above
1691,W13,760,125,2020-07-27,125.0,above
1692,W13,760,125,2020-07-27,125.0,above
1693,W13,760,125,2020-07-27,125.0,above
1694,W13,760,125,2020-07-27,125.0,above
1695,W13,760,125,2020-07-27,125.0,above
1696,W13,760,125,2020-07-27,125.0,above
1697,W13,760,125,2020-07-27,125.0,above
1698,W13,760,125,2020-07-27,125.0,above
1699,W13,760,125,2020-07-27,125.0,above
1700,W13,760,125,2020-07-27,125.0,above
1701,W13,760,125,2020-07-27,125.0,above
1702,W13,760,125,2020-07-27,125.0,above
1703,W13,760,125,2020-07-27,125.0,above
1704,W13,760,125,2020-07-27,125.0,above
1705,W13,760,125,2020-07-27,125.0,above
1706,W13,760,125,2020-07-27,125.0,above
1707,W13,760,125,2020-07-27,125.0,above
1708,W13,760,125,2020-07-27,125.0,above
1709,W13,760,125,2020-07-27,125.0,above
1710,W13,760,125,2020-07-27,125.0,above
0,W3,900,80,2020-06-08,80.0,below
1,W3,900,80,2020-06-08,80.0,below
2,W3,900,80,2020-06-08,80.0,below
86,W3,900,80,2020-06-22,80.0,below

In [58]:
df.is_daily_temp_over_10.value_counts()

above    1359
below     352
Name: is_daily_temp_over_10, dtype: int64

In [59]:
# get mean daily humidity
df["mean_daily_humid"]=df.groupby(["sensor_id","date"])["humidity"].transform(lambda row: row.mean())

In [60]:
# new df with one entry per day, only humidity vals
# get rolling mean to find prev. 10 days avergage
mean_daily_humid_df=df.drop_duplicates(subset=["date","sensor_id"],keep="first")[["sensor_id","date","mean_daily_humid"]]
mean_daily_humid_df["mean_10_days_humid"]=mean_daily_humid_df.groupby(["sensor_id"])["mean_daily_humid"].transform(lambda row: row.rolling(10).mean())

In [61]:
mean_daily_humid_df

     sensor_id        date  mean_daily_humid  mean_10_days_humid
3          W13  2020-06-16        900.000000                 NaN
9          W13  2020-06-19        900.000000                 NaN
21         W13  2020-06-20        900.000000                 NaN
65         W13  2020-06-21        900.000000                 NaN
84         W13  2020-06-22        900.000000                 NaN
107        W13  2020-06-23        900.000000                 NaN
149        W13  2020-06-24        900.000000                 NaN
199        W13  2020-06-25        900.000000                 NaN
217        W13  2020-06-26        900.000000                 NaN
262        W13  2020-06-27        900.000000          900.000000
308        W13  2020-06-28        900.000000          900.000000
352        W13  2020-06-29        794.800000          889.480000
402        W13  2020-06-30        457.173913          845.197391
448        W13  2020-07-01        576.488372          812.846229
491        W13  2020-07-02        614.066667          784.252895
536        W13  2020-07-03        612.387755          755.491671
585        W13  2020-07-04        521.622222          717.653893
630        W13  2020-07-05        385.458333          666.199726
678        W13  2020-07-06        486.756098          624.875336
719        W13  2020-07-07        526.408163          587.516152
768        W13  2020-07-08        522.354167          549.751569
816        W13  2020-07-09        557.386364          526.010205
860        W13  2020-07-10        515.260000          531.818814
910        W13  2020-07-11        476.960000          521.865977
960        W13  2020-07-12        456.619048          506.121215
1002       W13  2020-07-13        527.122449          497.594684
1051       W13  2020-07-14        595.145833          504.947045
1099       W13  2020-07-15        639.585366          530.359749
1140       W13  2020-07-16        604.000000          542.084139
1189       W13  2020-07-17        588.480769          548.291400
1241       W13  2020-07-18        735.488372          569.604820
1284       W13  2020-07-19        760.000000          589.866184
1333       W13  2020-07-20        760.000000          614.340184
1379       W13  2020-07-21        760.000000          642.644184
1428       W13  2020-07-22        760.000000          672.982279
1477       W13  2020-07-23        760.000000          696.270034
1518       W13  2020-07-24        760.000000          712.755451
1568       W13  2020-07-25        760.000000          724.796914
1620       W13  2020-07-26        760.000000          740.396914
1665       W13  2020-07-27        760.000000          757.548837
0           W3  2020-06-08        900.000000                 NaN
86          W3  2020-06-22        900.000000                 NaN

In [62]:
# say whether it's above or below 10
mean_daily_humid_df["humid_above_85"]=mean_daily_humid_df.apply(lambda row: "above" if (row["mean_10_days_humid"]/10 >85) else "below", axis=1)
mean_daily_humid_df.head(25)

    sensor_id        date  mean_daily_humid  mean_10_days_humid humid_above_85
3         W13  2020-06-16        900.000000                 NaN          below
9         W13  2020-06-19        900.000000                 NaN          below
21        W13  2020-06-20        900.000000                 NaN          below
65        W13  2020-06-21        900.000000                 NaN          below
84        W13  2020-06-22        900.000000                 NaN          below
107       W13  2020-06-23        900.000000                 NaN          below
149       W13  2020-06-24        900.000000                 NaN          below
199       W13  2020-06-25        900.000000                 NaN          below
217       W13  2020-06-26        900.000000                 NaN          below
262       W13  2020-06-27        900.000000          900.000000          above
308       W13  2020-06-28        900.000000          900.000000          above
352       W13  2020-06-29        794.800000          889.480000          above
402       W13  2020-06-30        457.173913          845.197391          below
448       W13  2020-07-01        576.488372          812.846229          below
491       W13  2020-07-02        614.066667          784.252895          below
536       W13  2020-07-03        612.387755          755.491671          below
585       W13  2020-07-04        521.622222          717.653893          below
630       W13  2020-07-05        385.458333          666.199726          below
678       W13  2020-07-06        486.756098          624.875336          below
719       W13  2020-07-07        526.408163          587.516152          below
768       W13  2020-07-08        522.354167          549.751569          below
816       W13  2020-07-09        557.386364          526.010205          below
860       W13  2020-07-10        515.260000          531.818814          below
910       W13  2020-07-11        476.960000          521.865977          below
960       W13  2020-07-12        456.619048          506.121215          below

In [63]:
# We want a final df that has sensor id, date, if daily temp > 10C, if past 10 days humidity >85%
final_df=df.drop(["humidity","temperature"],axis=1)
final_df=final_df.drop_duplicates(subset=["date","sensor_id"],keep="first")
final_df=final_df.merge(mean_daily_humid_df,on=["sensor_id","date","mean_daily_humid"],how='left')

In [64]:
final_df

,sensor_id,date,mean_daily_temp,is_daily_temp_over_10,mean_daily_humid,mean_10_days_humid,humid_above_85
0,W13,2020-06-16,80.000000,below,900.000000,NaN,below
1,W13,2020-06-19,80.000000,below,900.000000,NaN,below
2,W13,2020-06-20,80.000000,below,900.000000,NaN,below
3,W13,2020-06-21,80.000000,below,900.000000,NaN,below
4,W13,2020-06-22,80.000000,below,900.000000,NaN,below
5,W13,2020-06-23,80.000000,below,900.000000,NaN,below
6,W13,2020-06-24,80.000000,below,900.000000,NaN,below
7,W13,2020-06-25,80.000000,below,900.000000,NaN,below
8,W13,2020-06-26,80.000000,below,900.000000,NaN,below
9,W13,2020-06-27,80.000000,below,900.000000,900.000000,above
10,W13,2020-06-28,80.000000,below,900.000000,900.000000,above
11,W13,2020-06-29,117.060000,above,794.800000,889.480000,above
12,W13,2020-06-30,199.086957,above,457.173913,845.197391,below
13,W13,2020-07-01,191.534884,above,576.488372,812.846229,below
14,W13,2020-07-02,175.066667,above,614.066667,784.252895,below
15,W13,2020-07-03,175.836735,above,612.387755,755.491671,below
16,W13,2020-07-04,185.377778,above,521.622222,717.653893,below
17,W13,2020-07-05,220.937500,above,385.458333,666.199726,below
18,W13,2020-07-06,179.048780,above,486.756098,624.875336,below
19,W13,2020-07-07,177.040816,above,526.408163,587.516152,below
20,W13,2020-07-08,200.708333,above,522.354167,549.751569,below
21,W13,2020-07-09,190.454545,above,557.386364,526.010205,below
22,W13,2020-07-10,209.000000,above,515.260000,531.818814,below
23,W13,2020-07-11,225.460000,above,476.960000,521.865977,below
24,W13,2020-07-12,217.071429,above,456.619048,506.121215,below
25,W13,2020-07-13,214.510204,above,527.122449,497.594684,below
26,W13,2020-07-14,187.520833,above,595.145833,504.947045,below
27,W13,2020-07-15,184.048780,above,639.585366,530.359749,below
28,W13,2020-07-16,205.408163,above,604.000000,542.084139,below
29,W13,2020-07-17,208.288462,above,588.480769,548.291400,below
30,W13,2020-07-18,136.930233,above,735.488372,569.604820,below
31,W13,2020-07-19,125.000000,above,760.000000,589.866184,below
32,W13,2020-07-20,125.000000,above,760.000000,614.340184,below
33,W13,2020-07-21,125.000000,above,760.000000,642.644184,below
34,W13,2020-07-22,125.000000,above,760.000000,672.982279,below
35,W13,2020-07-23,125.000000,above,760.000000,696.270034,below
36,W13,2020-07-24,125.000000,above,760.000000,712.755451,below
37,W13,2020-07-25,125.000000,above,760.000000,724.796914,below
38,W13,2020-07-26,125.000000,above,760.000000,740.396914,below
39,W13,2020-07-27,125.000000,above,760.000000,757.548837,below
40,W3,2020-06-08,80.000000,below,900.000000,NaN,below
41,W3,2020-06-22,80.000000,below,900.000000,NaN,below

In [69]:
# Alert only if both are triggered
#final_df['both triggered']=final_df.apply(lambda row: "ALERT" if (row["is_daily_temp_over_10"]=="below" and row["humid_above_85"]=="above") else "", axis=1)

final_df['both triggered']=final_df.apply(lambda row: "ALERT" if (row["is_daily_temp_over_10"]=="below" and row["humid_above_85"]=="above") else ("Warning" if (((10<row['mean_daily_temp']<150) and (75<row["mean_10_days_humid"]<850))) else ""), axis=1)

In [70]:
final_df

,sensor_id,date,mean_daily_temp,is_daily_temp_over_10,mean_daily_humid,mean_10_days_humid,humid_above_85,both triggered
0,W13,2020-06-16,80.000000,below,900.000000,NaN,below,
1,W13,2020-06-19,80.000000,below,900.000000,NaN,below,
2,W13,2020-06-20,80.000000,below,900.000000,NaN,below,
3,W13,2020-06-21,80.000000,below,900.000000,NaN,below,
4,W13,2020-06-22,80.000000,below,900.000000,NaN,below,
5,W13,2020-06-23,80.000000,below,900.000000,NaN,below,
6,W13,2020-06-24,80.000000,below,900.000000,NaN,below,
7,W13,2020-06-25,80.000000,below,900.000000,NaN,below,
8,W13,2020-06-26,80.000000,below,900.000000,NaN,below,
9,W13,2020-06-27,80.000000,below,900.000000,900.000000,above,ALERT
10,W13,2020-06-28,80.000000,below,900.000000,900.000000,above,ALERT
11,W13,2020-06-29,117.060000,above,794.800000,889.480000,above,
12,W13,2020-06-30,199.086957,above,457.173913,845.197391,below,
13,W13,2020-07-01,191.534884,above,576.488372,812.846229,below,
14,W13,2020-07-02,175.066667,above,614.066667,784.252895,below,
15,W13,2020-07-03,175.836735,above,612.387755,755.491671,below,
16,W13,2020-07-04,185.377778,above,521.622222,717.653893,below,
17,W13,2020-07-05,220.937500,above,385.458333,666.199726,below,
18,W13,2020-07-06,179.048780,above,486.756098,624.875336,below,
19,W13,2020-07-07,177.040816,above,526.408163,587.516152,below,
20,W13,2020-07-08,200.708333,above,522.354167,549.751569,below,
21,W13,2020-07-09,190.454545,above,557.386364,526.010205,below,
22,W13,2020-07-10,209.000000,above,515.260000,531.818814,below,
23,W13,2020-07-11,225.460000,above,476.960000,521.865977,below,
24,W13,2020-07-12,217.071429,above,456.619048,506.121215,below,
25,W13,2020-07-13,214.510204,above,527.122449,497.594684,below,
26,W13,2020-07-14,187.520833,above,595.145833,504.947045,below,
27,W13,2020-07-15,184.048780,above,639.585366,530.359749,below,
28,W13,2020-07-16,205.408163,above,604.000000,542.084139,below,
29,W13,2020-07-17,208.288462,above,588.480769,548.291400,below,
30,W13,2020-07-18,136.930233,above,735.488372,569.604820,below,Warning
31,W13,2020-07-19,125.000000,above,760.000000,589.866184,below,Warning
32,W13,2020-07-20,125.000000,above,760.000000,614.340184,below,Warning
33,W13,2020-07-21,125.000000,above,760.000000,642.644184,below,Warning
34,W13,2020-07-22,125.000000,above,760.000000,672.982279,below,Warning
35,W13,2020-07-23,125.000000,above,760.000000,696.270034,below,Warning
36,W13,2020-07-24,125.000000,above,760.000000,712.755451,below,Warning
37,W13,2020-07-25,125.000000,above,760.000000,724.796914,below,Warning
38,W13,2020-07-26,125.000000,above,760.000000,740.396914,below,Warning
39,W13,2020-07-27,125.000000,above,760.000000,757.548837,below,Warning
40,W3,2020-06-08,80.000000,below,900.000000,NaN,below,
41,W3,2020-06-22,80.000000,below,900.000000,NaN,below,